version: "3"

services:
  teslamate:
    image: teslamate/teslamate:1.20
    restart: always
    env_file: ./.env
    environment:
      - DATABASE_HOST=database
      - MQTT_HOST=mqtt
    ports:
      - 4000:4000
    cap_drop:
      - all

  database:
    image: postgres:13
    restart: always
    env_file: ./.env
    volumes:
      - /media/shared/postgres/data:/var/lib/postgresql/data:rw

  grafana:
    image: mghiold/tesla-solar:1.6
    restart: always
    env_file: ./.env
    user: 115:122
    environment:
      - DATABASE_HOST=database
      - PGID=122
      - PUID=115
    ports:
      - 3000:3000
    volumes:
      - /media/shared/grafana:/var/lib/grafana:rw

